FROM continuumio/miniconda3:4.12.0

WORKDIR /usr/src/app

COPY environment.yml .

RUN conda env create -f environment.yml

ENV PATH="/opt/conda/envs/dnn/bin/:${PATH}"
ENV CONDA_DEFAULT_ENV dnn
ENV CONDA_PREFIX /opt/conda/env/dnn

EXPOSE 8800