name: dnn
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pandas
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  # Interactive
  - ipykernel
  - matplotlib
  - seaborn
  # Testing
  - pycodestyle
  - pytest
  - pytest-cov
  - pytest-pycodestyle
  # Pip
  - pip
